name: "Install packages"
description: "Install required packages"

runs:
  using: "composite"
  steps:
    - name: Install Linux dependencies (raylib)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -euxo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libx11-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          libxext-dev \
          libxrender-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          mesa-common-dev

        # Optional but often helpful on Ubuntu runners
        sudo apt-get install -y --no-install-recommends xorg-dev

        # quick sanity check (so we SEE it in logs)
        dpkg -l | grep -E "libx11-dev|libxrandr-dev" || true

    - name: Install Clang ${{ matrix.clang_ver }}
      if: runner.os == 'Linux' && matrix.runs_msan == true
      uses: nick-fields/retry@v3
      with:
        shell: bash
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: |
          set -euxo pipefail
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh ${{ matrix.clang_ver }}

    - name: Install libc++ (Linux Clang ${{ matrix.clang_ver }})
      if: runner.os == 'Linux' && matrix.runs_msan == true
      shell: bash
      run: |
        set -euxo pipefail
        sudo apt-get install -y --no-install-recommends \
          libc++-${{ matrix.clang_ver }}-dev \
          libc++abi-${{ matrix.clang_ver }}-dev

    - name: Install valgrind
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      shell: bash
      run: |
        set -euxo pipefail
        sudo apt-get install -y --no-install-recommends valgrind
