name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    # Common Linux dependencies
    - name: Install Linux dependencies (raylib)
      if: runner.os == 'Linux'
      shell: bash
      run: |
       sudo apt-get update
       sudo apt-get install -y --no-install-recommends \
       libx11-dev \
       libxrandr-dev \
       libxinerama-dev \
       libxcursor-dev \
       libxi-dev \
       libxext-dev \
       libxrender-dev \
       libgl1-mesa-dev \
       libglu1-mesa-dev \
       mesa-common-dev \
       xorg-dev

    # Also see https://github.com/actions/runner-images/discussions/9446#discussioncomment-8668538
    - name: Install Clang ${{ matrix.clang_ver }}
      if: runner.os == 'Linux' && matrix.runs_msan == true
      uses: nick-fields/retry@v3
      with:
        shell: bash
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh ${{ matrix.clang_ver }}

    - name: Install libc++ (Linux Clang ${{ matrix.clang_ver }})
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_msan == true
      run: |
        sudo apt-get install --no-install-recommends \
          libc++-${{ matrix.clang_ver }}-dev \
          libc++abi-${{ matrix.clang_ver }}-dev

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        sudo apt-get install --no-install-recommends valgrind
